---
abstract: 'Client for GCIS Structured Data Server'
author:
  - unknown
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.131560'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gcis-Client
provides:
  Gcis::Client:
    file: lib/Gcis/Client.pm
    version: 0.08
requires:
  JSON::XS: 0
  Mojo::UserAgent: 0
  Path::Class: 0
  Time::HiRes: 0
  YAML::XS: 0
version: 0.08
